### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by redgluten** [tannernelson/vapor#10]
I’m just getting started here so maybe it’s just my setup. Right now I get this error when I try to build vapor:

```swift
Cloning https://github.com/tannernelson/vapor.git
Using version 0.1.4 of package vapor
error: rename error: File exists (17): /var/www/vapor/Packages/vapor -> /var/www/vapor/Packages/vapor-0.1.4
```

This Ubuntu 14.04 with clang, git, libicu-dev installed. Swift 2.2 from January 11 is installed too.

**Comment by tannernelson** [comment]
Try `rm -rf Packages` 

I think this is an error with SPM.

**Comment by redgluten** [comment]
No changes. Still the same error.

**Comment by tannernelson** [comment]
From Ubuntu 14.04

```shell
tanner@Albert:~/test$ git clone git@github.com:tannernelson/vapor-example.git
Cloning into 'vapor-example'...
remote: Counting objects: 154, done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 154 (delta 37), reused 0 (delta 0), pack-reused 77
Receiving objects: 100% (154/154), 3.59 MiB | 0 bytes/s, done.
Resolving deltas: 100% (69/69), done.
Checking connectivity... done.
tanner@Albert:~/test$ cd vapor-example/
tanner@Albert:~/test/vapor-example$ swift build
Cloning https://github.com/tannernelson/vapor.git
Using version 0.1.4 of package vapor
Compiling Swift Module 'Vapor' (18 sources)
Linking Library:  .build/debug/Vapor.a
Compiling Swift Module 'VaporApp' (2 sources)
Linking Executable:  .build/debug/VaporApp
tanner@Albert:~/test/vapor-example$ 
```

I am running Swift 3.0, but that shouldn't be changing anything. I was using 2.2 just a few days ago.

```shell
tanner@Albert:~/test/vapor-example$ swift --version
Swift version 3.0-dev (LLVM f95d47afa7, Clang f66c5bb67b, Swift b745691a38)
Target: x86_64-unknown-linux-gnu
```

**Comment by redgluten** [comment]
I forgot to say that I’m running Ubuntu using vagrant maybe it’s an issue with file sharing? 

In the meantime I’m running Vapor from OS X, works great. 👍

**Comment by tannernelson** [comment]
I've successfully used it on Ubuntu 15.10 with VirtualBox. 

But possibly if you're mapping the files using Vagrant that could be creating an issue. Maybe some permissions stuff. Try cloning it in a non-shared directory and see if that works. 

Glad to hear it's working on OS X. :)

**Comment by hex20** [comment]
Yeah i'm also having the same vagrant issue

**Comment by tannernelson** [comment]
The Swift Package Manager is still in its early phases. :\

Swift has a bug tracker at https://bugs.swift.org/secure/Dashboard.jspa You should report your Vagrant setup (config files, version, etc) there alongside the full error message. 

The main SPM repository is here https://github.com/apple/swift-package-manager

**Comment by hex20** [comment]
@redgluten you just need to set your shared folder on your host OS to `chmod 777`

**Comment by tannernelson** [comment]
@hex20 great find.

**Comment by redgluten** [comment]
@hex20 Ok I’ll try that thanks.
