### ISSUE TITLE
compile fail, ubuntu 14.04

### ISSUE THREAD

**Issue by alloyapple** [tannernelson/vapor#11]
swift build
Compiling Swift Module 'Vapor' (18 sources)
/home/mac/swiftdev/vapor/Sources/Parser.swift:36:42: error: value of type 'String' has no member 'stringByReplacingOccurrencesOfString'
                    let key = cookieArray[0].stringByReplacingOccurrencesOfString(" ", withString: "")
                              ~~~~~~~~~~~^~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by tannernelson** [comment]
Can you paste the output of "swift --version" ?
