### ISSUE TITLE
Asynchronous

### ISSUE THREAD

**Issue by elliottminns** [tannernelson/vapor#12]
I would like to propose an improvement that would allow for asynchronous request handling. 

My proposal would be that instead of returning a `ResponseConvertible` object in the Router, a `Response` object is added to the parameters, and is handled when a `send()` method is called on the response. For example: 

```swift 
Route.get("/") { request, response in
      response.status = .OK
      response.body = View(path: "Views/index.html")
      response.send()
}
```

This would allow for any asynchronous long running tasks to be handled, whilst giving the ability to return to the user in a timely manner. This would allow for much more responsive websites. For example:

```swift 
Route.post("/BuildRome") { request, response in

    if builder.validateData(request.data) {

        response.status = .OK

        builder.buildRomeFromData(request.data) { rome in
             
             // Tell the world we've built rome. 
             response.body = ["rome": rome]
             response.send()
        }

    } else {
        response.status = . BadRequest
        response.send()
    }
}
```

Please let me know your thoughts.

**Comment by tannernelson** [comment]
I like this idea. I'd like to continue to support the current interface, though. I think the async response is less common. 

Possibly a 'Route.getAsync("")' or 'Route.get("").async("")' API would work.

**Comment by elliottminns** [comment]
It should be possible to support both without having different interfaces defined using function overloading.

```swift

// Sync
Router.post("") { request in
    return Response()
}

// Async
Router.post("") { request, response in 
    response.send()
}

```

**Comment by tannernelson** [comment]
I'm not at a computer right now to see if Swift would complain about the params to the closure not matching. But I know it will complain if the closure doesn't return a `Response`.. 

Possibly an `AsyncResponse` object could be returned with a closure inside.

**Comment by tannernelson** [comment]
@elliottminns Just saw the note about function overloading. You're right. I think that would work.

**Comment by elliottminns** [comment]
Awesome, I'll get started on this on my fork.

**Comment by elliottminns** [comment]
I've managed to implement this however with one caveat. I get this build error for using my old sync methods now such as 
```swift
Route.get("/") { request in
    let view = try View(path: "Views/index.html")
    return view
}
```


```
/Project/Sources/main.swift:9:1: error: ambiguous use of 'get(_:closure:)'
Route.get("/") { request in
^
Vapor.Route:4:23: note: found this candidate
    public class func get(path: String, closure: Vapor.Route.Type.Closure)
                      ^
Vapor.Route:5:23: note: found this candidate
    public class func get(path: String, closure: Vapor.Route.Type.ResponseClosure)
                      ^
<unknown>:0: error: build had 1 command failures
```

It seems that while the async method works fine, the interface for the sync method is now too ambiguous for the compiler. This can be solved by explicitly defined which closure type it is, however this does take away from the cleanliness of the original interface and will be breaking for any current code:

```swift
Route.get("/") { (request) -> ResponseConvertible in
    let view = try View(path: "Views/index.html")
    return view
}   
```

It may be cleaner therefore to instead add a `Route.async.get()` or `Route.getAsync()` method instead to preserve the original interface.

Let me know your thoughts

**Comment by tannernelson** [comment]
Can you create a pull request with the changes?

**Comment by tannernelson** [comment]
https://github.com/tannernelson/vapor/commit/6b033dfe582c68477e7ff806a1b401ede0df50b7 fixes this.
