### ISSUE TITLE
Error while deploying to Heroku

### ISSUE THREAD

**Issue by s0mmer** [tannernelson/vapor#18]
First of all, good job on making this!

This issue might be out of scope for this repo, but here goes. I wanted to try and deploy this to Heroku. Using kylef's buildpack (https://github.com/kylef/heroku-buildpack-swift) I receive the following error:
```
remote: -----> Fetching set buildpack https://github.com/kylef/heroku-buildpack-swift.git... done
remote: -----> Swift app detected
remote: -----> Installing 2.2-SNAPSHOT-2016-01-11-a
remote: -----> Installing clang-3.7.0
remote: -----> Building Package
remote: Cloning https://github.com/tannernelson/vapor.git
remote: Using version 0.1.6 of package vapor
remote: Compiling Swift Module 'Vapor' (21 sources)
remote: /tmp/build_40ef44289550a82b4ac7bc7f6206a753/Packages/vapor-0.1.6/Sources/Server.swift:85:17: error: use of unresolved identifier 'sleep'
remote:                 sleep(1)
remote:                 ^~~~~
remote: Attributes 'readnone and readonly' are incompatible!
remote: i16 (i16)* @htons
remote: LLVM ERROR: Broken module found, compilation aborted!
remote: <unknown>:0: error: build had 1 command failures
remote: swift-build: error: exit(1): ["/tmp/build_40ef44289550a82b4ac7bc7f6206a753/.swift/swift-2.2-SNAPSHOT-2016-01-11-a/swift-2.2-SNAPSHOT-2016-01-11-a-ubuntu14.04/usr/bin/swift-build-tool", "-f", "/tmp/build_40ef44289550a82b4ac7bc7f6206a753/.build/release/Vapor.o/llbuild.yaml"]
remote:
remote:
remote:  !     Push rejected, failed to compile Swift app
```

Do you know why this is happening?

**Comment by tannernelson** [comment]
There's an issue with the Clang compiler right now that is throwing this error when compiling `release`

```shell
remote: Attributes 'readnone and readonly' are incompatible!
remote: i16 (i16)* @htons
```

The only solution for that currently on Linux is to compile in development / debug mode. 


As for the other error  ```remote: /tmp/build_40ef44289550a82b4ac7bc7f6206a753/Packages/vapor-0.1.6/Sources/Server.swift:85:17: error: use of unresolved identifier 'sleep'
remote:                 sleep(1)```

I have never seen this before. It must be an issue with `#if os(Linux)` being resolved because `sleep()` is a part of `import Glibc` I'm pretty sure.

**Comment by tannernelson** [comment]
Just checked the file and it looked like `import Glibc` was inadvertently removed from that file. It has been re-added. And i'm force setting the `0.1.6` release to contain that fix. 

If you compile the Heroku app again without `--configuration release` you should be good to go.

**Comment by tannernelson** [comment]
Actually, I just found a way to avoid using `htons()` altogether. It's now building properly on `--configuration release`.

**Comment by s0mmer** [comment]
It works, thanks a lot 🙏🎉
