### ISSUE TITLE
create documentation wiki

### ISSUE THREAD

**Issue by tannernelson** [tannernelson/vapor#21]
Vapor, like Laravel, needs to have excellent documentation. The first step will be separating out the current single documentation README into multiple sections and pages. A GitHub wiki will be a good place to start with this as the Markdown format could be easily ported to a full website in the future. 

Additionally, information such as a roadmap / contribution guideline will be included in this expanded documentation.

**Comment by tannernelson** [comment]
@mpclarkson feel free to add any initial thoughts you have for a roadmap here.

**Comment by mpclarkson** [comment]
Here are some initial thoughts, in no particular order:
- Event / Listener system
- Logging
- Websockets
- Authentication / authorization
- File uploads 
- Console / generator (e.g. vapor new project, vapor generate:controller Users etc, vapor scaffold users etc)
- Fluent ORM - relationships, associations, other DB support

Sorry if any of these are already implemented - I haven't read the source in detail yet.

WRT contribution guidelines:
- What coding style should be followed? e.g. https://github.com/github/swift-style-guide
- US English should be used in code and documentation (I'm Aussie and my auto correct keeps changing `Vapor` to `Vapour`, `Authorize` to `Authorise` etc  )

**Comment by tannernelson** [comment]
https://github.com/tannernelson/vapor/wiki
