### ISSUE TITLE
Vapor installer

### ISSUE THREAD

**Issue by mpclarkson** [tannernelson/vapor#27]
Not an issue as such, more of an FYI...

I've built a quick installer here https://github.com/mpclarkson/vapor-installer which allows you to create a new vapor project at the command line:

 `vapor new ProjectName`

This basically:
1. Checks if a folder with the specified name exists already
2. Clones your vapor-example repository (master) into a folder with the `ProjectName`
3. Updates the `Package.swift` and other files by replacing `VaporApp` with `ProjectName`

Future enhancements:
1. Specify a tag / release
2. Self-update etc

Note, I had to build this with `swiftc` rather than `swift build` as I'm having all sorts of issues with the package manager on OSX- no issues on Ubuntu.

Let me know if you'd be happy for me to update the readme with a link to the installer.

Are you on twitter?

**Comment by tannernelson** [comment]
Yes this looks great, please add this to the README.

And yeah, my twitter is @tanner0101
