### ISSUE TITLE
Decode URL-encoded parameters in request.parameters

### ISSUE THREAD

**Issue by kylebshr** [tannernelson/vapor#32]
It would be nice if parameters were automatically decoded — almost every web framework does this automatically. I would make a PR but the repo seems to be missing main.swift and several other other items — is that on purpose?

**Comment by artkay** [comment]
For the `main.swift` - here is explanations from [the older issue:](https://github.com/tannernelson/vapor/issues/20#issuecomment-181129980)

> Files like main.swift can't be included in the repo, or they will make the module compile as an executable instead of a library which will make it incompatible with the Swift Package Manager.

If you want to add something to `main.swift` - maybe it's better to create a PR for [vapor-example](https://github.com/tannernelson/vapor-example)?

**Comment by tannernelson** [comment]
The `main.swift` file is included in the `.gitignore` so you can safely add one to Vapor for testing without worrying about it getting committed to GitHub.

1. Fork vapor
2. Add `main.swift` 
3. Fix URL decoding
4. Test
5. Submit PR

**Comment by kylebshr** [comment]
Implemented in #33
