### ISSUE TITLE
JSONSerializer not working with Array<String: Any>.

### ISSUE THREAD

**Issue by tuanphung** [tannernelson/vapor#37]
Hi,

When I tried to return an object with type is Array<[String: Any]> like this:

```swift
override func index(request: Request) -> ResponseConvertible {
	return generate()
}
func generate() -> Array<[String: Any]> {
	let firstObject: [String: Any] = ["id": 1, "title": "first"]
	let secondObject: [String: Any] = ["id": 2, "title": "second"] 
	return [firstObject, secondObject]
}
```
It doesn't work!

I looked into JSONSerializer class, I see the type casting to `[Any]` always fail.
```swift
else if let arr = object as? [Any] {
```

I think it's a bug of Swift. So, as work-around, I added some codes to make it work.
```swift
else if let arr = object as? Array<[String: Any]> {
// Do same things as [Any]
}
```

Your library is awesome, keep it up :)
Tuan.

**Comment by tannernelson** [comment]
We're currently working on a comprehensive solution to this problem here: https://github.com/tannernelson/vapor/pull/35

Swift on Linux has a bug right now where it doesn't recognize dictionaries as `[String: Any]`.
