### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by glock45** [tannernelson/vapor#44]
Hi @tannernelson 

I thought you learn something from: https://github.com/glock45/swifter/issues/88#issuecomment-173759182 but you did not :/

**Again** you violate license by copying source code from (https://github.com/glock45/swifter):

Examples:
Swifter: https://github.com/glock45/swifter/blob/master/Sources/String%2BSHA1.swift#L21
V: https://github.com/tannernelson/vapor/blob/master/Sources/Hash.swift#L58

Swifter: https://github.com/glock45/swifter/blob/master/Sources/String%2BMisc.swift
V: https://github.com/tannernelson/vapor/blob/master/Sources/StringExtensions.swift

Swifter: https://github.com/glock45/swifter/blob/master/Sources/HttpRequest.swift#L27
V: https://github.com/tannernelson/vapor/blob/master/Sources/RequestFormExtension.swift

Swifter: https://github.com/glock45/swifter/blob/master/Sources/Socket.swift
V: https://github.com/tannernelson/vapor/blob/master/Sources/Socket.swift ( it's not "Based on", it's just 90%-one-to-one copy without license headers ).

How long it will last ?

**Comment by tannernelson** [comment]
Fixed in #45.
