### ISSUE TITLE
Use node HTTP-parser

### ISSUE THREAD

**Issue by tannernelson** [tannernelson/vapor#6]
Look into using https://github.com/nodejs/http-parser with a module map for HTTP parsing.

**Comment by rabc** [comment]
Using [Zewo's HTTPParser](https://github.com/Zewo/HTTPParser) is an option?

**Comment by tannernelson** [comment]
@rabc That would also be an option. 

My main concern is ensuring that Vapor doesn't rely on users installing any C libraries to get up and running. I'm still trying to find a good solution for this.
